# GitHub CI build pipeline
name: ml project CI

on:
  push:
    branches:
      - master
      - main
      - dev
      - qa
  pull_request:
    branches:
      - master
      - main
      - dev
      - qa
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
        if  [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Unit Tests and generate coverage report
      run: |
        python -m unittest -v
        coverage run -m unittest
        coverage report
        coverage html
    - name: Archive code coverage html report
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: src/htmlcov
    - name: Run package creation
      run: |
        python -m pip install wheel setuptools
        python setup.py bdist_wheel
    - name: Archive package
      uses: actions/upload-artifact@v2
      with:
        name: mlpackage
        path: src/dist